In [1]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [2]:
import os # To use os functions
import matplotlib.pyplot as plt #To plot
import joblib  #To save or model
import numpy as np

plt.style.use("fivethirtyeight")


In [6]:
'''
Variable eta is used for learning rate and variable epochs is used for
number of iterations.
Big weights may take time to update so to keep the weights small multiply it 
with 1e-4. 
In bias we can any value other than -1 but generally people use -1..
'''
class Perceptron:
    def __init__(self, eta:float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta =eta #learning rate
        self.epochs = epochs #iterations
        
        
    def fit(self, X,y):    
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")

In [10]:
obj = Perceptron(eta=0.01, epochs=10)

In [11]:
obj.eta

0.01

In [12]:
obj.epochs

10

In [13]:
obj.weights

array([-4.37553961e-05,  8.82078749e-05,  4.76044723e-05])

In [16]:
X = np.ones((4,2))

In [17]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
y = np.ones((4,1))

In [19]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [20]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
